import Cocoa
import SwiftUI
import Speech
import AVFoundation
struct TaskRow:Codable,Identifiable{var id:String;var title:String;var state:String;var detail:String;var updated:Int;var source:String;var thread:String;var url:String;var today:Bool;var next:String;var label:String}
struct CommandRow:Codable,Identifiable{var id:String;var text:String;var target:String;var status:String;var reply:String;var thread:String}
struct Board:Codable{var generated:Int;var date:String;var errors:[String];var tasks:[TaskRow];var model:String;var commands:[CommandRow]?;var ivy_online:Bool?}
struct Receipt:Decodable{var ok:Bool;var message:String}
final class Model:ObservableObject{
 @Published var board:Board?;@Published var error="";@Published var busy=false;@Published var sending=false;@Published var sendNote="";@Published var delivered=false
 let root=(Bundle.main.object(forInfoDictionaryKey:"IvySourceRoot") as? String ?? NSHomeDirectory()+"/ivy")+"/80_操盘手/工具/桌面任务板/"
 func load(){do{let d=try Data(contentsOf:URL(fileURLWithPath:NSHomeDirectory()+"/Library/Application Support/IvyTaskBoard/board.json"));board=try JSONDecoder().decode(Board.self,from:d);error=""}catch{self.error="任务记录暂时不可读"}}
 func run(_ args:[String]=["sync"]){guard !busy else{return};busy=true;DispatchQueue.global(qos:.utility).async{let p=Process();p.executableURL=URL(fileURLWithPath:"/usr/bin/python3");p.arguments=[self.root+"sync.py"]+args;p.standardOutput=FileHandle.nullDevice;p.standardError=FileHandle.nullDevice;var ok=false;do{try p.run();p.waitUntilExit();ok=p.terminationStatus==0}catch{};let success=ok;DispatchQueue.main.async{self.busy=false;self.load();if !success{self.error="同步失败 · 保留上次记录"}}}}
 func send(_ text:String,target:String,channel:String){guard !sending,!text.trimmingCharacters(in:.whitespacesAndNewlines).isEmpty else{return};let defaults=UserDefaults.standard;var request=["text":text,"target_id":target,"channel":channel];if let old=defaults.dictionary(forKey:"pendingEnvelope") as? [String:String],old["text"]==text,old["target_id"]==target,old["channel"]==channel{request=old}else{request["id"]=UUID().uuidString;defaults.set(request,forKey:"pendingEnvelope")};guard let bytes=try? JSONSerialization.data(withJSONObject:request) else{return};sending=true;delivered=false;sendNote="正在提交…"
 DispatchQueue.global(qos:.userInitiated).async{let p=Process();let input=Pipe();let output=Pipe();p.executableURL=URL(fileURLWithPath:"/usr/bin/python3");p.arguments=[self.root+"desktop_input.py"];p.standardInput=input;p.standardOutput=output;p.standardError=FileHandle.nullDevice;var receipt:Receipt?;do{try p.run();input.fileHandleForWriting.write(bytes);try input.fileHandleForWriting.close();let data=output.fileHandleForReading.readDataToEndOfFile();p.waitUntilExit();receipt=try JSONDecoder().decode(Receipt.self,from:data)}catch{};let result=receipt;DispatchQueue.main.async{self.sending=false;self.sendNote=result?.message ?? "发送未确认，原文已保留";self.delivered=result?.ok ?? false;if self.delivered{defaults.removeObject(forKey:"pendingEnvelope")};self.run()}}}
 func mark(_ t:TaskRow,_ s:String){run(["mark","--id",t.id,"--state",s])}
 func today(_ t:TaskRow){run(["today","--id",t.id]+(t.today ? ["--off"]:[]))}
}
func statusColor(_ s:String)->Color{switch s{case "running":return Color(red:0.13,green:0.48,blue:0.38);case "waiting":return .orange;case "blocked":return .red;default:return .secondary}}
struct Content:View{
 @StateObject var model=Model();@State var filter="当前";@State var source="全部";@State var expanded:String?=nil;@State var target:TaskRow?=nil;@State var channel="auto";@StateObject var speech=SpeechInput();@State var voiceBase="";@State var receipts=false;@State var floating=false;@AppStorage("commandDraft") var draft=""
 let timer=Timer.publish(every:15,on:.main,in:.common).autoconnect()
 var tasks:[TaskRow]{model.board?.tasks ?? []}
 var visible:[TaskRow]{tasks.filter{t in var cal=Calendar(identifier:.gregorian);cal.timeZone=TimeZone(identifier:"Asia/Shanghai")!;let today=cal.isDate(Date(timeIntervalSince1970:Double(t.updated)),inSameDayAs:Date());let match=(filter=="运行中" && t.state=="running") || (filter=="当前" && ["running","pending","waiting","blocked"].contains(t.state)) || filter=="全部" || (filter=="今天" && t.state != "saved" && (t.today || today || t.state=="running")) || (filter=="未完成" && !["done","saved","paused","review"].contains(t.state)) || (filter=="待核验" && t.state=="review") || (filter=="已完成" && t.state=="done");return match && (source=="全部" || t.source==source)}}
 var body:some View{
 VStack(alignment:.leading,spacing:12){
 HStack{VStack(alignment:.leading,spacing:3){Text("任务面板").font(.system(size:25,weight:.bold,design:.rounded));Text(model.board?.date ?? "读取中").font(.system(size:11)).foregroundColor(.secondary)};Spacer();Button{floating.toggle();NotificationCenter.default.post(name:Notification.Name("WidgetLevel"),object:floating)}label:{Image(systemName:floating ? "rectangle.on.rectangle.fill":"square.bottomthird.inset.filled")}.help(floating ? "贴回桌面":"临时浮起");Button{model.run()}label:{Image(systemName:"arrow.clockwise")}.disabled(model.busy).help("刷新");Menu{Button("小号"){resize(420,660)};Button("大号"){resize(480,800)};Divider();Button("退出"){NSApp.terminate(nil)}}label:{Image(systemName:"ellipsis")}.menuStyle(.borderlessButton).frame(width:20)}.buttonStyle(.plain)
 HStack(spacing:0){stat("正在做",tasks.filter{$0.state=="running"}.count,.green);stat("等你处理",tasks.filter{$0.state=="waiting"}.count,.orange);stat("卡住了",tasks.filter{$0.state=="blocked"}.count,.red);stat("待继续",tasks.filter{$0.state=="pending"}.count,.secondary)}
 HStack{Picker("来源",selection:$source){ForEach(["全部","Codex","Claude","Grok"],id:\.self){Text($0)}}.pickerStyle(.segmented).labelsHidden();Spacer(minLength:10);Menu(filter){ForEach(["当前","运行中","今天","未完成","待核验","已完成","全部"],id:\.self){f in Button(f){filter=f}}}.frame(width:96)}
 if !model.error.isEmpty{Text(model.error).font(.caption).foregroundColor(.red)}
 if let errors=model.board?.errors,!errors.isEmpty{Text(errors.joined(separator:"；")).font(.caption).foregroundColor(.red)}
 ScrollView{LazyVStack(alignment:.leading,spacing:9){if receipts{ForEach(model.board?.commands ?? []){c in receiptCard(c)}}else{ForEach(visible){t in taskCard(t)}};if !receipts && visible.isEmpty{Text("这里暂时没有任务").font(.caption).foregroundColor(.secondary).frame(maxWidth:.infinity).padding(35)}}.padding(.bottom,4)}
 commandBox
 HStack{Circle().fill(model.board?.ivy_online==true ? .green:.orange).frame(width:5,height:5);Text(model.board?.ivy_online==true ? "Ivy 在线":"Ivy 暂未在线");Spacer();Button(receipts ? "任务列表":"发送记录"){receipts.toggle()}.buttonStyle(.plain);Text("· \(visible.count) 项");Text(timeText(model.board?.generated ?? 0))}.font(.system(size:10)).foregroundColor(.secondary)
 }.padding(18).frame(minWidth:400,minHeight:600).background(Color(red:0.95,green:0.96,blue:0.94).opacity(0.97)).clipShape(RoundedRectangle(cornerRadius:24)).overlay(RoundedRectangle(cornerRadius:24).stroke(.white.opacity(0.8),lineWidth:1)).preferredColorScheme(.light).onAppear{model.load();model.run()}.onReceive(timer){_ in model.run()}.onChange(of:model.delivered){_,v in if v{draft=""}}.onChange(of:speech.text){_,v in if !v.isEmpty{draft=voiceBase+(voiceBase.isEmpty ? "":"\n")+v}}
 }
 var commandBox:some View{VStack(alignment:.leading,spacing:8){
 HStack{Image(systemName:"square.and.pencil").foregroundColor(.green);Text(target == nil ? "新任务":target!.title).font(.system(size:12,weight:.semibold)).lineLimit(1);Spacer();if target != nil{Button{target=nil;model.sendNote=""}label:{Image(systemName:"xmark.circle.fill")}.buttonStyle(.plain)}}
 ZStack(alignment:.topLeading){if draft.isEmpty{Text("输入任务…").foregroundColor(.secondary).padding(.top,7).padding(.leading,5)};TextEditor(text:$draft).font(.system(size:13)).scrollContentBackground(.hidden).frame(height:56).accessibilityLabel("Ivy 指令输入")}
 HStack{if target==nil{Picker("执行渠道",selection:$channel){Text("自动分派").tag("auto");Text("Codex").tag("codex");Text("Claude").tag("claude_app");Text("Grok CLI").tag("grok_cli")}.labelsHidden().frame(width:120)}else{Text("续接原任务").font(.caption).foregroundColor(.secondary)};Text(model.sendNote).font(.system(size:10)).foregroundColor(.secondary).lineLimit(1);Spacer(minLength:2);Button{if speech.recording{speech.stop()}else{voiceBase=draft;speech.start()}}label:{Image(systemName:speech.recording ? "stop.circle.fill":"mic.fill").foregroundColor(speech.recording ? .red:.secondary)}.buttonStyle(.plain).help(speech.recording ? "停止语音输入":"语音输入").accessibilityLabel(speech.recording ? "停止语音输入":"语音输入").disabled(speech.requesting || model.sending);Button{model.send(draft,target:target?.id ?? "",channel:channel)}label:{Text(model.sending ? "提交中":"发送").font(.system(size:12,weight:.semibold))}.buttonStyle(.borderedProminent).tint(Color(red:0.15,green:0.42,blue:0.33)).disabled(model.sending || speech.recording || speech.requesting || draft.trimmingCharacters(in:.whitespacesAndNewlines).isEmpty).keyboardShortcut(.return,modifiers:.command)}
 if !speech.note.isEmpty{Text(speech.note).font(.system(size:10)).foregroundColor(speech.failed ? .red:.secondary)}
 }.padding(12).background(.white.opacity(0.85)).cornerRadius(14)}
 func taskCard(_ t:TaskRow)->some View{VStack(alignment:.leading,spacing:7){HStack(alignment:.top,spacing:7){Circle().fill(statusColor(t.state)).frame(width:6,height:6).padding(.top,5);Text(t.title).font(.system(size:13,weight:.semibold)).lineLimit(expanded==t.id ? nil:2).help(t.title);Spacer(minLength:3);Text(t.label).font(.system(size:10)).foregroundColor(statusColor(t.state))};Text(t.detail).font(.system(size:11)).foregroundColor(.secondary).lineLimit(expanded==t.id ? nil:2).fixedSize(horizontal:false,vertical:true);HStack(spacing:9){Text(t.source+" · "+timeText(t.updated)).font(.system(size:10)).foregroundColor(.secondary);Spacer(minLength:0);Button("继续"){target=t;receipts=false;model.sendNote=""};Button(expanded==t.id ? "收起":"展开"){expanded=expanded==t.id ? nil:t.id};Menu{if t.source != "Claude" && !t.thread.isEmpty{Button("打开原聊天"){openCodex(t.thread)}};Button(t.today ? "移出今天":"今天做"){model.today(t)};Button("标记完成"){model.mark(t,"done")};Button("待继续"){model.mark(t,"pending")};Button("等我处理"){model.mark(t,"waiting")};Button("暂停"){model.mark(t,"paused")}}label:{Image(systemName:"ellipsis")}.menuStyle(.borderlessButton).frame(width:18)}.font(.system(size:11)).buttonStyle(.plain)}.padding(12).frame(maxWidth:.infinity,alignment:.leading).background(.white.opacity(0.68)).cornerRadius(12)}
 func receiptCard(_ c:CommandRow)->some View{VStack(alignment:.leading,spacing:7){HStack{Text(c.target).font(.caption).foregroundColor(.secondary);Spacer();Text(c.status).font(.caption).foregroundColor(.green)};Text(c.text).font(.system(size:13,weight:.medium)).lineLimit(3);Text(c.reply).font(.system(size:12)).foregroundColor(.secondary).lineLimit(expanded==c.id ? nil:3);HStack{Button(expanded==c.id ? "收起":"展开"){expanded=expanded==c.id ? nil:c.id};Spacer();if !c.thread.isEmpty{Button("执行回执"){openCodex(c.thread)}}}.font(.caption)}.padding(12).background(.white.opacity(0.65)).cornerRadius(12)}
 func stat(_ label:String,_ count:Int,_ color:Color)->some View{VStack(alignment:.leading,spacing:2){Text("\(count)").font(.system(size:23,weight:.semibold,design:.rounded)).foregroundColor(color);Text(label).font(.system(size:10)).foregroundColor(.secondary)}.frame(maxWidth:.infinity,alignment:.leading)}
 func openCodex(_ id:String){if let u=URL(string:"codex://threads/"+id){NSWorkspace.shared.open(u)}}
 func resize(_ width:CGFloat,_ height:CGFloat){NSApp.windows.filter{$0.title=="我的任务"}.forEach{w in var f=w.frame;f.origin.y += f.height-height;f.size=NSSize(width:width,height:height);w.setFrame(f,display:true,animate:true)}}
 func timeText(_ stamp:Int)->String{guard stamp>0 else{return "—"};let f=DateFormatter();f.timeZone=TimeZone(identifier:"Asia/Shanghai");f.dateFormat=Calendar.current.isDateInToday(Date(timeIntervalSince1970:Double(stamp))) ? "HH:mm":"M/d HH:mm";return f.string(from:Date(timeIntervalSince1970:Double(stamp)))}
}
class DesktopPanel:NSPanel{override var canBecomeKey:Bool{true};override var canBecomeMain:Bool{false}}
class Delegate:NSObject,NSApplicationDelegate{
 var window:DesktopPanel!;var status:NSStatusItem!
 let desktopLevel=NSWindow.Level(rawValue:Int(CGWindowLevelForKey(.desktopIconWindow))+1)
 func applicationDidFinishLaunching(_ notification:Notification){
 if NSRunningApplication.runningApplications(withBundleIdentifier:"com.lashimao.ivy-task-board").count>1{NSApp.terminate(nil);return}
 window=DesktopPanel(contentRect:NSRect(x:0,y:0,width:460,height:760),styleMask:[.borderless,.nonactivatingPanel],backing:.buffered,defer:false)
 window.title="我的任务";window.isOpaque=false;window.backgroundColor = .clear;window.hasShadow=true;window.hidesOnDeactivate=false;window.isFloatingPanel=false;window.isMovableByWindowBackground=true;window.collectionBehavior=[.canJoinAllSpaces,.stationary,.ignoresCycle];window.level=desktopLevel;window.setFrameAutosaveName("IvyDesktopWidgetV2")
 if UserDefaults.standard.string(forKey:"NSWindow Frame IvyDesktopWidgetV2")==nil,let s=NSScreen.main{let f=s.visibleFrame;window.setFrameOrigin(NSPoint(x:f.maxX-480,y:f.maxY-780))};window.contentView=NSHostingView(rootView:Content());window.orderFrontRegardless()
 NotificationCenter.default.addObserver(forName:Notification.Name("WidgetLevel"),object:nil,queue:.main){[weak self]n in guard let self=self else{return};self.window.level=(n.object as? Bool)==true ? .floating:self.desktopLevel;self.window.orderFrontRegardless()}
 let main=NSMenu();let item=NSMenuItem();main.addItem(item);let menu=NSMenu();menu.addItem(withTitle:"退出我的任务",action:#selector(NSApplication.terminate(_:)),keyEquivalent:"q");item.submenu=menu;let editItem=NSMenuItem();let edit=NSMenu(title:"编辑");edit.addItem(withTitle:"剪切",action:#selector(NSText.cut(_:)),keyEquivalent:"x");edit.addItem(withTitle:"复制",action:#selector(NSText.copy(_:)),keyEquivalent:"c");edit.addItem(withTitle:"粘贴",action:#selector(NSText.paste(_:)),keyEquivalent:"v");edit.addItem(withTitle:"全选",action:#selector(NSText.selectAll(_:)),keyEquivalent:"a");editItem.submenu=edit;main.addItem(editItem);NSApp.mainMenu=main
 status=NSStatusBar.system.statusItem(withLength:NSStatusItem.squareLength);status.button?.image=NSImage(systemSymbolName:"checklist",accessibilityDescription:"我的任务");let sm=NSMenu();sm.addItem(withTitle:"显示桌面组件",action:#selector(show),keyEquivalent:"").target=self;sm.addItem(withTitle:"退出",action:#selector(NSApplication.terminate(_:)),keyEquivalent:"");status.menu=sm
 }
 @objc func show(){window.orderFrontRegardless()}
 func applicationShouldHandleReopen(_ sender:NSApplication,hasVisibleWindows flag:Bool)->Bool{show();return true}
}
@main
struct TaskBoardMain { static func main() {
if CommandLine.arguments.count==3 && CommandLine.arguments[1]=="--speech-file" { runSpeechFileProbe(CommandLine.arguments[2]); return }
let app=NSApplication.shared;let delegate=Delegate();app.delegate=delegate;app.setActivationPolicy(.accessory);app.run()

}}
